server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/th-user
    username: jezhsing
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true